"""Automated job discovery and bidding loop for the 0rbit OpenClaw agent.

Blueprint binding
- Section 14 Phase 4 Item 6 (E2E posted job → automated bid)
- Section 9.3 (AXL bid message schema)

This module polls the backend jobs endpoint, filters by the agent's declared
capabilities, emits bids over AXL, and records the bid in the backend audit log.

GAP notes
- Discovery poll interval is not defined in the blueprint; default is set to 10s
  and documented as a GAP for downstream tuning.
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field
from typing import Any, Dict, Optional

import httpx

from agents.plugins.orbit.axl_client import AXLClient
from agents.plugins.orbit.sender import send_bid
from agents.plugins.orbit.storage import upload_data
from agents.plugins.orbit.compute import submit_for_verification
from agents.plugins.orbit.sender import send_output_ready
from agents.plugins.orbit.messages import JobAcceptedPayload

__all__ = ["JobHandler"]


logger = logging.getLogger(__name__)

DISCOVERY_INTERVAL_SECONDS = 10  # GAP: blueprint does not specify a poll cadence
DEFAULT_BID_MESSAGE = "Automated bid generated by OpenClaw agent"


@dataclass
class JobHandler:
    """Poll jobs, match capabilities, and place bids via AXL + backend audit."""

    axl: AXLClient
    agent_ens: str
    agent_peer_id: str
    capabilities: list[str]
    _bid_cache: set[str] = field(default_factory=set, init=False, repr=False)

    async def discover_jobs(self, base_url: str) -> list[Dict[str, Any]]:
        """Fetch posted jobs filtered by capability intersection."""

        params: list[tuple[str, str]] = [("status", "posted")]
        for capability in self.capabilities:
            params.append(("capabilities[]", capability))

        try:
            async with httpx.AsyncClient(base_url=base_url, timeout=10.0) as client:
                response = await client.get("/v1/jobs", params=params)
                response.raise_for_status()
        except httpx.HTTPError as exc:  # pragma: no cover - network failure
            raise RuntimeError("Failed to discover jobs from backend") from exc

        payload = response.json() or {}
        jobs = payload.get("data") or []
        matched = [job for job in jobs if self._job_matches(job)]
        return matched

    def _job_matches(self, job: Dict[str, Any]) -> bool:
        required = job.get("required_capabilities") or []
        if not required:
            return bool(self.capabilities)
        return all(capability in self.capabilities for capability in required)

    async def bid_on_job(
        self,
        job: Dict[str, Any],
        proposed_amount: str,
        dst_peer_id: str,
        base_url: str,
    ) -> Dict[str, Any]:
        """Send an AXL bid and persist audit trail via backend POST /bids."""

        job_id = str(job.get("id")) if job.get("id") is not None else None
        if not job_id:
            raise ValueError("Job payload missing id; cannot bid")

        axl_response = await send_bid(
            self.axl,
            self.agent_peer_id,
            dst_peer_id,
            job_id,
            proposed_amount,
            self.capabilities,
            self.agent_ens,
        )
        axl_message_id = None
        if isinstance(axl_response, dict):
            axl_message_id = axl_response.get("message_id")

        bid_payload = {
            "proposed_amount": proposed_amount,
            "message": DEFAULT_BID_MESSAGE,
            "axl_message_id": axl_message_id,
        }

        endpoint = f"/v1/jobs/{job_id}/bids"
        try:
            async with httpx.AsyncClient(base_url=base_url, timeout=10.0) as client:
                response = await client.post(endpoint, json=bid_payload)
                response.raise_for_status()
        except httpx.HTTPError as exc:  # pragma: no cover - network failure
            raise RuntimeError(f"Failed to record bid for job {job_id}") from exc

        audit_record = response.json() or {}
        logger.info("Bid submitted for job %s (axl_message_id=%s)", job_id, axl_message_id)
        self._bid_cache.add(job_id)
        return audit_record

    async def execute_job(self, job: Dict[str, Any]) -> bytes:
        """Placeholder job execution hook until agent-specific runtime is defined."""

        job_id = str(job.get("job_id")) if job.get("job_id") is not None else "unknown"
        return b"Mock job output for " + job_id.encode()

    async def handle_job_accepted(
        self,
        msg: JobAcceptedPayload,
        dst_peer_id: str,
        base_url: str,
    ) -> Dict[str, Any]:
        """Execute accepted job, upload output, verify with 0G, and notify backend + AXL."""

        job_endpoint = f"/v1/jobs/{msg.job_id}"
        async with httpx.AsyncClient(base_url=base_url, timeout=10.0) as client:
            response = await client.get(job_endpoint)
            response.raise_for_status()
            job_payload = response.json() or {}

        result_bytes = await self.execute_job({"job_id": msg.job_id, **job_payload})

        og_root = upload_data(result_bytes, filename=f"job_{msg.job_id}")
        output_hash, compute_proof = await submit_for_verification(result_bytes)

        await send_output_ready(
            self.axl,
            self.agent_peer_id,
            dst_peer_id,
            msg.job_id,
            output_hash,
            og_root,
        )

        complete_payload = {
            "output_hash": output_hash,
            "compute_proof": compute_proof.hex(),
        }

        async with httpx.AsyncClient(base_url=base_url, timeout=10.0) as client:
            response = await client.post(f"/v1/jobs/{msg.job_id}/complete", json=complete_payload)
            response.raise_for_status()
            return response.json() or {}

    async def run_discovery_loop(
        self,
        base_url: str,
        *,
        interval: int = DISCOVERY_INTERVAL_SECONDS,
        proposed_amount: str = "100",
    ) -> None:
        """Continuously discover jobs and place bids (infinite loop)."""

        if interval <= 0:
            raise ValueError("interval must be a positive integer")

        while True:
            try:
                jobs = await self.discover_jobs(base_url)
            except Exception as exc:  # pragma: no cover - logging path
                logger.warning("Job discovery failed: %s", exc, exc_info=exc)
                jobs = []

            for job in jobs:
                job_id = str(job.get("id")) if job.get("id") is not None else None
                if not job_id:
                    logger.debug("Skipping job with missing id: %s", job)
                    continue
                if job_id in self._bid_cache:
                    continue

                dst_peer_id = job.get("poster_peer_id")
                if not dst_peer_id:
                    logger.debug("Skipping job %s due to missing poster_peer_id", job_id)
                    continue

                try:
                    await self.bid_on_job(job, proposed_amount, dst_peer_id, base_url)
                except Exception as exc:  # pragma: no cover - logging path
                    logger.warning("Failed to bid on job %s: %s", job_id, exc, exc_info=exc)

            await asyncio.sleep(interval)
